---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  jshint:
    enabled: true
  markdownlint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "*.js"
  - "api/**/*.js"
  - "config/**/*.js"
  - "**/*.md"
exclude_paths:
  - "api/responses/*.js"