FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Exia Secu Demo

Exia Secu Demo is a backend, RESTful API.
It's intended to be coupled with a frontend application.
The whole project is a security leak demonstration for 
Grand Nord Digital Forum: we're playing a "token theft" 
showing the matter of data encryption when it comes to HTTP.

## Users [/user]

Available on `/user`

+ Attributes
    + id : 12 (number) - Autoincrement
    + email: w.white@polloshermanos.us (string, required) - Will also act as the user login
    + password: theonewhoknocks (string, required) - Encrypted
    + fistname: Walter (string)
    + lastname: WHITE (string)
    + createdAt: `2016-03-10T16:51:47.008Z` (string) - Automatic, ISO 8601
    + updatedAt: `2016-03-10T17:55:03.047Z` (string) - Automatic, ISO 8601

### List [GET /user]

+ Request
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Response 200 (application/json)

        [
            {
                id: 12,
                email: 'w.white@polloshermanos.us',
                surname: 'Walter',
                lastname: 'WHITE',
                createdAt: '2016-03-10T16:51:47.008Z',
                updatedAt: '2016-03-10T16:51:47.008Z'
            },
            {
                id: 13,
                email: 'j.pinkman@polloshermanos.us',
                surname: 'Jessee',
                lastname: 'PINKMAN',
                createdAt: '2016-03-10T17:55:03.047Z',
                updatedAt: '2016-03-10T17:55:03.047Z'
            }
        ]

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

### Find [GET /user/{id}]

+ Request
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Parameters
    + id : 12 (number) - User id to retrieve

+ Response 200 (application/json)

        {
            id: 12,
            email: 'w.white@polloshermanos.us',
            surname: 'Walter',
            lastname: 'WHITE',
            createdAt: '2016-03-10T16:51:47.008Z',
            updatedAt: '2016-03-10T16:51:47.008Z'
        }

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

+ Response 404

    The resource at `id` does not exist
    
    + Body

### Create [POST /user]

+ Attributes
    + email: w.white@polloshermanos.us (string, required)
    + password: theonewhoknocks (string, required)
    + fistname: Walter (string)
    + lastname: WHITE (string)

+ Request (application/x-www-form-urlencoded)
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Request (application/json)
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Response 201 (application/json)
    + Headers

            Location: /user/12

    + Body
    
            {
                id: 12,
                email: 'w.white@polloshermanos.us',
                surname: 'Walter',
                lastname: 'WHITE',
                createdAt: '2016-03-10T16:51:47.008Z',
                updatedAt: '2016-03-10T16:51:47.008Z'
            }

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

+ Response 400

    Malformed object
    
    + Body

### Update [PUT /user/{id}]

+ Parameters
    + id : 12 (number) - User id to retrieve

+ Attributes
    + email: w.white@polloshermanos.us (string, required)
    + password: theonewhoknocks (string, required)
    + fistname: Walter (string)
    + lastname: WHITE (string)

+ Request (application/x-www-form-urlencoded)
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Request (application/json)
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Response 200 (application/json)

        {
            id: 12,
            email: 'w.white@polloshermanos.us',
            surname: 'Walter',
            lastname: 'WHITE',
            createdAt: '2016-03-10T16:51:47.008Z',
            updatedAt: '2016-03-10T16:51:47.008Z'
        }

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

+ Response 404

    The resource at `id` does not exist
    
    + Body

+ Response 400

    Malformed object
    
    + Body

### Delete [DELETE /user/{id}]

+ Request
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Parameters
    + id : 12 (number) - User id to retrieve

+ Response 200 (application/json)

        {
            email: 'w.white@polloshermanos.us',
            surname: 'Walter',
            lastname: 'WHITE',
            createdAt: '2016-03-10T16:51:47.008Z',
            updatedAt: '2016-03-10T16:51:47.008Z'
        }

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

+ Response 404

    The resource at `id` does not exist
    
    + Body




## Customers [/customer]

Available on `/customer`

+ Attributes
    + id : 7 (number) - Autoincrement
    + name: Los Pollos Hermanos (string, required)
    + createdAt: `2016-08-11T03:23:08.002Z` (string) - Automatic, ISO 8601
    + updatedAt: `2016-09-11T15:39:01.025Z` (string) - Automatic, ISO 8601

### List [GET /customer]

+ Request
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Response 200 (application/json)

        [
            {
                id: 7,
                name: 'Los Pollos Hermanos',
                createdAt: '2016-08-11T03:23:08.002Z',
                updatedAt: '2016-09-11T15:39:01.025Z'
            },
            {
                id: 8,
                name: 'Saul Goodman Associates',
                createdAt: '2016-08-11T18:15:16.030Z',
                updatedAt: '2016-08-11T19:21:12.054Z'
            }
        ]

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

### Find [GET /customer/{id}]

+ Request
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Parameters
    + id : 7 (number) - Customer id to retrieve

+ Response 200 (application/json)

        {
            id: 7,
            name: 'Los Pollos Hermanos',
            createdAt: '2016-08-11T03:23:08.002Z',
            updatedAt: '2016-09-11T15:39:01.025Z'
        }

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

+ Response 404

    The resource at `id` does not exist
    
    + Body

### Create [POST /customer]

+ Attributes
    + name: Los Pollos Hermanos (string, required)

+ Request (application/x-www-form-urlencoded)
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Request (application/json)
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Response 201 (application/json)
    + Headers

            Location: /customer/7

    + Body
    
            {
                id: 7,
                name: 'Los Pollos Hermanos',
                createdAt: '2016-08-11T03:23:08.002Z',
                updatedAt: '2016-09-11T15:39:01.025Z'
            }

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

+ Response 400

    Malformed object
    
    + Body

### Update [PUT /customer/{id}]

+ Parameters
    + id : 7 (number) - Customer id to retrieve

+ Attributes
    + name: Los Pollos Hermanos (string, required)

+ Request (application/x-www-form-urlencoded)
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Request (application/json)
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Response 200 (application/json)

        {
            id: 7,
            name: 'Los Pollos Hermanos',
            createdAt: '2016-08-11T03:23:08.002Z',
            updatedAt: '2016-09-11T15:39:01.025Z'
        }

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

+ Response 404

    The resource at `id` does not exist
    
    + Body

+ Response 400

    Malformed object
    
    + Body

### Delete [DELETE /customer/{id}]

+ Request
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Parameters
    + id : 7 (number) - Customer id to retrieve

+ Response 200 (application/json)

        {
            name: 'Los Pollos Hermanos',
            createdAt: '2016-08-11T03:23:08.002Z',
            updatedAt: '2016-09-11T15:39:01.025Z'
        }

+ Response 403

    Provided access token is not allowed for the resource
    
    + Body

+ Response 404

    The resource at `id` does not exist
    
    + Body




## Authentication [/auth]

Available on `/auth`

### Sign in [POST /auth/signin]

+ Attributes
    + email: w.white@polloshermanos.us (string, required)
    + password: theonewhoknocks (string, required)

+ Request (application/x-www-form-urlencoded)

+ Request (application/json)

+ Response 200 (application/json)

        {
            token: 'OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP'
        }

+ Response 404

    No user exist with this `email`
    
    + Body

+ Response 400

    Password does not match with user's
    
    + Body

### Find my profile [GET /auth/me]

+ Request
    + Headers

            token: OiJzaHFkb3cifQ.255bI2f5F_GGrwc9avZP

+ Response 200 (application/json)

        {
            email: 'w.white@polloshermanos.us',
            surname: 'Walter',
            lastname: 'WHITE',
            createdAt: '2016-03-10T16:51:47.008Z',
            updatedAt: '2016-03-10T16:51:47.008Z'
        }

+ Response 403

    This token was not granted for any user, or is not anymore
    
    + Body